### ISSUE TITLE
Unity spinning descent animation

### ISSUE THREAD

**Issue by faintray123** [NameTaken3125/ACUFixes#1]
hi can you give me your discord? Hello, i  would like to ask you to make a more frequent descent from the rope 360 with a wall hook, this animation can not be repeated anywhere and it works only in some places, you can’t do them yourself anywhere , I'll throw off a link here as it looks like, I have several videos where they are. In Sndicat, you can already use them often, I would like to use them in the unit. If it's possible to do it, could you implement it in a Unity game?

**Comment by faintray123** [comment]
If you can do it, you are the best, i with my friend love this beautiful animation, it’s really OP

**Comment by NameTaken3125** [comment]
Hi,
I've looked into it. Version [0.3.0](https://github.com/NameTaken3125/ACUFixes/releases/tag/v0.3.0) contains an optional feature (turn it on in the mod menu under "Personal requests") to make the Spinning Descent happen more frequently. I cannot make it happen _everywhere_, but the chance for it to play has been increased greatly.
When swinging on a horizontal bar, ropes between buildings etc., hold Sprint+Forward+ParkourDown.
See the gif: https://imgur.com/a/IAYEa1I
If this action is available at all (if the in-game scanner has found an appropriate grab point, which does happen very often), it _will_ be used.
As everything else, this was only tested in singleplayer.

**Comment by faintray123** [comment]
еTHX MAN YOU ARE THE BEST give ME YOU DISCORD PLZ !!!!




сб, 20 мая 2023 г. в 11:58, NameTaken3125 ***@***.***>:

**Comment by faintray123** [comment]
man you need to send this m od in NEXUS you are so awesome!!!!!!!!!!


сб, 20 мая 2023 г. в 16:51, faintray ***@***.***>:

**Comment by faintray123** [comment]
its doesont work((((


сб, 20 мая 2023 г. в 16:55, faintray ***@***.***>:

**Comment by NameTaken3125** [comment]
Please describe the problem.
- Which version of the game are you using?
- Which version of the mod?
- What goes wrong?
- Does the mod even start, or does the game crash? (You might be the first person to try it out)
I got a [Discord server](https://discord.gg/FjGA58dHDj) or you can post here.

**Comment by faintray123** [comment]
Hi! Can you do parkour mod for Wotch Dogs2?

**Comment by NameTaken3125** [comment]
Hello. There are no plans for any other games, sorry.
Also, closing this issue since the original request has been implemented and problems seem to have been resolved.
