### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by shadooww** [NameTaken3125/ACUFixes#4]
hi, I really appreciate your work, could you make it so you can use your hidden blade in more situations? like when u throw a smoke bomb and nobody sees you you could use your hidden blade instead of you sword?

**Comment by NameTaken3125** [comment]
Hello,
This has been requested.
I don't think I want to allow assassinations every time an enemy is smoked. Smoke bombs are already way overpowered for a "realistic" playstyle.
However, what you suggest, "when nobody sees you", as in "assassinate the couple of last enemies standing if they are smoked", would perhaps be a slightly more fair situation to allow this.
I might consider this, but I so far have no idea how to tell how many enemies I'm in conflict with/am seen by.

**Comment by chxxlk** [comment]
Hey, thanks for the cool mod! Can you also make a hotkey dive helper for controllers? Thanks btw.

**Comment by NameTaken3125** [comment]
Hi, I hope you're having fun.
I might be able to add _some_ support for controllers. For now, several users have reported successfully using Steam or DS4Windows to remap their controller buttons.

**Comment by chxxlk** [comment]
That sounds awesome.
Thanks for the info. Maybe I'll do the same thing as some other users.

**Comment by Nicolas-Delebarre** [comment]
I just downloaded and use the mod, and is awesome!!, there will be an option to fix lod's in this game? nowdays some GPUs are really powerfull and i think they can handle heavier LODs in a mutch longer distance.

**Comment by Symbellmund** [comment]
I just downloaded and use the mod, and is awesome!!, there will be an option to fix lod's in this game? nowdays some GPUs are really powerfull and i think they can handle heavier LODs in a mutch longer distance.

**Comment by NameTaken3125** [comment]
Hello [Symbellmund](https://github.com/Symbellmund) and thank you :)
I have not touched graphics and I don't think I will. There already exists a [LOD FIX](https://www.nexusmods.com/assassinscreedunity/mods/121) mod. Perhaps that one does what you want?

**Comment by Symbellmund** [comment]
> Hello [Symbellmund](https://github.com/Symbellmund) and thank you :) I have not touched graphics and I don't think I will. There already exists a [LOD FIX](https://www.nexusmods.com/assassinscreedunity/mods/121) mod. Perhaps that one does what you want?

thanks very mutch that is what I searched !!
