### ISSUE TITLE
Mod does not seem to seem to work

### ISSUE THREAD

**Issue by FitchTV** [NameTaken3125/ACUFixes#5]
On steam, 1.5.0, downloaded the github and NM version , neither are working? It launches the game but insert doesnt open any menu, r and H dont do anything, added firewall exceptions, AV exceptions, any suggestions

**Comment by NameTaken3125** [comment]
Hello,
Do you see the text in the top left corner? If not, the mod failed to inject.
Try running the Loader after the game starts.
If that doesn't help, try running as administrator.

**Comment by FitchTV** [comment]
crashed the game on me doing that, the launcher always crashes the game if it is already running

**Comment by NameTaken3125** [comment]
Sorry about that. I'm working on an autoloader.
For now, try doing some of [these things](https://forums.nexusmods.com/index.php?showtopic=13009455/#entry125824395).

You don't happen to have Visual Studio installed?

**Comment by FitchTV** [comment]
I'm not sure how I would check that, it aint showing up in the windows key search

**Comment by FitchTV** [comment]
deleting autoexec fixed it, thanks man, I also launched the game and then the loader as the four assassins popped up

**Comment by NameTaken3125** [comment]
Regarding the Visual Studio: it probably means you don't have it. That's ok.
What is the autoexec?
